### ISSUE TITLE
Set method is not working

### ISSUE THREAD

**Issue by arnoldou** [leafsphp/leafMVC#1]
I installed the leafMVC framework to give it a try. I wanted to pass data from the controller to the view using:
$this->set(["name" =>"Mike"]);

and receive error : 
Fatal error: Uncaught Error: Call to undefined method Leaf\Veins\Template::assign() in C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\controller.php:64 Stack trace: #0 C:\xampp\htdocs\leaf-facturacion\app\controllers\UsuariosController.php(19): Leaf\Core\Controller->set(Array) #1 [internal function]: App\Controllers\UsuariosController->index() #2 C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\leaf.php(338): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\leaf.php(311): Leaf\Core\Leaf->invoke('UsuariosControl...', Array) #4 C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\leaf.php(251): Leaf\Core\Leaf->handle(Array, true) #5 C:\xampp\htdocs\leaf-facturacion\app\routes\web.php(25): Leaf\Core\Leaf->run() #6 C:\xampp\htdocs\leaf-facturacion\config\routes.php(7): require('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\leaf-facturacion\index.php(53): require('C:\\xampp\\htdocs...') #8 {main} thrown in C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\controller.php on line 64

**Comment by mr-phlames** [comment]
I believe it might be the version of Leaf that comes with the LeafMVC package you installed. Instead of `set`, try `assign`. Let's see if this works

**Comment by arnoldou** [comment]
assign() method is not working too.  I installed leafMVC with composer. What version should I use

error:
Fatal error: Uncaught Error: Call to undefined method App\Controllers\UsuariosController::assign() in C:\xampp\htdocs\leaf-facturacion\app\controllers\UsuariosController.php:13 Stack trace: #0 [internal function]: App\Controllers\UsuariosController->index() #1 C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\leaf.php(338): call_user_func_array(Array, Array) #2 C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\leaf.php(311): Leaf\Core\Leaf->invoke('UsuariosControl...', Array) #3 C:\xampp\htdocs\leaf-facturacion\vendor\leafs\leaf\src\core\leaf.php(251): Leaf\Core\Leaf->handle(Array, true) #4 C:\xampp\htdocs\leaf-facturacion\app\routes\web.php(25): Leaf\Core\Leaf->run() #5 C:\xampp\htdocs\leaf-facturacion\config\routes.php(7): require('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\leaf-facturacion\index.php(53): require('C:\\xampp\\htdocs...') #7 {main} thrown in C:\xampp\htdocs\leaf-facturacion\app\controllers\UsuariosController.php on line 13

**Comment by mr-phlames** [comment]
Run this command in the root of your project `composer require leafs/leaf ^1.5.0-alpha`

**Comment by mr-phlames** [comment]
This will install a version of Leaf suitable for LeafMVC, let me know if this works. Sorry, for the inconvenience🙏

**Comment by arnoldou** [comment]
Yes.. now it is working .. using the set() method. Thanks a lot. Keep working in this project, I like it. Would be nice to  have a full small project using  all the features of the framework. Keep going...

**Comment by mr-phlames** [comment]
Thanks and good luck with your project.
