### ISSUE TITLE
Replacement of abandoned fzaninotto/faker

### ISSUE THREAD

**Issue by divineniiquaye** [leafsphp/leafMVC#10]
## Description

The package [fzaninotto/faker][1] is abandoned and no longer maintained. No replacement package was suggested. However, since this package is used widely including this repository. Laravel has a maintained fork of it. Read more at https://laravel-news.com/changes-coming-to-php-faker.

# Expected Behavior or Solution

I expect that [fakerphp/faker](https://github.com/fakerphp/faker) be used as a replacement and also with its latest version.

[1]: https://github.com/fzaninotto/faker

**Comment by mychidarko** [comment]
Thanks, I'll read more on it and make the required changes 🙏🏽

**Comment by mychidarko** [comment]
This was helpful. It has been fixed now and a new preview version will be released soon. In the mean time, you can install the v3.x branch and that will apply all the fixes made.
