### ISSUE TITLE
It does not support for php 8.0

### ISSUE THREAD

**Issue by jdesousa1** [leafsphp/leafMVC#14]
![image](https://user-images.githubusercontent.com/17109527/146033591-175a0330-21be-47b2-8a6f-c86995b30d2b.png)

Update dependeces that use deployer.

Deployer has support for php 8.0.

**Comment by mychidarko** [comment]
Hi, @jdesousa1 thanks for reaching out. Unfortunately version 2 of leaf MVC does not yet support php 8. For now, you can use the leaf MVC 3 release candidate

You can install it with composer 

```sh
composer create-project leafs/mvc project-name v3.0-rc
```
