### ISSUE TITLE
The set() method is not passing an object to the view.

### ISSUE THREAD

**Issue by arnoldou** [leafsphp/leafMVC#2]
when I pass a single value to the view it works but when I want to pass an object it doesn´t:

public function index() {              
            $user = (object) [
                "name" => "Jane Doe",
                "email" => "janedoe@gmail.com",
                "verified" => true
            ];    
          
            $this->set($user);
            $this->render("usuarios/prueba");
        }

// in my view:

<p>Hi {$user->name}</p>
   <p>email: {$user->email}</p>

**Comment by mr-phlames** [comment]
What's the exact error you're getting?
Also, have you checked whether `{$object.key}` is working.
