### ISSUE TITLE
Uncaught Error: Class "Leaf\View" not found in public/index.php:69

### ISSUE THREAD

**Issue by facu-alba** [leafsphp/leafMVC#32]
Hi! I am using leafs api. When doing composer install the error occurred: Uncaught Error: Class "Leaf\View" not found in public/index.php:69

Help! Thanks

**Comment by mychidarko** [comment]
Hi @facu-alba, looks like you're on an older version of Leaf API. You'll have to replace the Leaf\View line with the following:

```php
Leaf\Config::attachView(\Leaf\Blade::class);
```

Potentially, you may have to update your `config/view.php` file to look like this too https://github.com/leafsphp/leafAPI/blob/v3.x/config/view.php

**Comment by mychidarko** [comment]
Hi @facu-alba any feedback?

**Comment by facu-alba** [comment]
@mychidarko thank you! Now works 🎉

**Comment by mychidarko** [comment]
Awesome 👏🏾
