### ISSUE TITLE
Undefined array key "X-Leaf-CSRF-Token"

### ISSUE THREAD

**Issue by pera-programer** [leafsphp/leafMVC#33]
Hi,

I have installed leafs/mvc project. Also I have installed auth:scaffold for authentication. Then I have run the server via leaf serve command and I'm getting start screen page. But the issue is when I navigate to /auth/login or /auth/register I get the following error message: 

Undefined array key "X-Leaf-CSRF-Token" (View: /app/views/pages/auth/login.blade.php) 
so the code breaks down here  <?php csrf()->form(); ?>
And when I go to csrf()->form() I see it outputs 
echo '<input type="hidden" name="' . static::$config['secretKey'] . '" value="' . $_SESSION[static::$config['secretKey']] . '" />';
and when I var_dump $_SESSION it doesn't have that key, only  { ["leaf"]=> array(1) { ["flash"]=> NULL } } 

I also tried to change in config/cors.php 'secretKey' => 'X-Leaf-CSRF-Token', for example to be 'secretKey' => 'X-CSRF-Token' but noting happens, still getting the same issue  whether 'secretKey' was changed or not

So what to do here?

**Comment by mychidarko** [comment]
Issue has been fixed @pera-programer. You can run `composer install` to clear the error

**Comment by pera-programer** [comment]
I have checked, now it is working I can register new user and then login 
Thanks @mychidarko for fix
