### ISSUE TITLE
 Command "g:middleware" is not defined.

### ISSUE THREAD

**Issue by pera-programer** [leafsphp/leafMVC#35]
From documentation https://leafphp.dev/docs/routing/middleware/mvc.html
When I run command
php leaf g:middleware LogRequest
I get the following error message:
Command "g:middleware" is not defined.

**Comment by mychidarko** [comment]
@pera-programer updating leafs/aloe should fix this issue. You can run:

```bash
leaf install aloe
```

Or with composer:

```bash
composer require leafs/aloe
```

**Comment by pera-programer** [comment]
It's working now. Thanks
