### ISSUE TITLE
Sessions not persist on reload

### ISSUE THREAD

**Issue by arnoclr** [leafsphp/leafMVC#5]
![image](https://user-images.githubusercontent.com/45895096/88467360-8bae4a80-ced6-11ea-9526-6e90d5760de5.png)
With `leafs/leaf` classic, session id is filled, but here is still empty. When I reload, all the values disappear.`$_SESSION` not work also.

```php
$session = new \Leaf\Http\Session;
$session->set('test', 'true');
dd($_SESSION);
```

**Comment by mychidarko** [comment]
Hello @Aryqs-Ipsum, sorry about this. I also chanced upon this problem while working with Leaf MVC. This issue will be fixed completely in next release of Leaf, however, for now, a simple work-around is to call `session_start()` before initializing `Leaf\Http\Session`

```php
session_start();
$session = new \Leaf\Http\Session;
$session->set('test', 'true');
$session->get('test');
```

**Comment by arnoclr** [comment]
Hello, I try your solution but I've an other error : 

`Fatal error: Uncaught ErrorException: session_id(): Cannot change session id when session is active in C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php:175 Stack trace: #0 [internal function]: Leaf\App::handleErrors(2, 'session_id(): C...', 'C:\\xampp\\htdocs...', 175, Array) #1 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php(175): session_id('884rm99pjaj56i1...') #2 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php(16): Leaf\Http\Session->id() #3 C:\xampp\htdocs\App\Controllers\LoginController.php(39): Leaf\Http\Session->__construct() #4 [internal function]: App\Controllers\LoginController->mail() #5 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\App.php(754): call_user_func_array(Array, Array) #6 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\App.php(727): Leaf\App->invoke('LoginController...', Array) #7 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\App.php(1297): Leaf\App->handle(Array, true) #8 C:\xampp\htdocs\index.php(107): Leaf\App->run() #9 {main} thrown in C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php on line 175`

**Comment by arnoclr** [comment]
little update, classic session work when i do a `session_start()`

**Comment by mychidarko** [comment]
Are you starting the session in your `LoginController`?

**Comment by arnoclr** [comment]
> Are you starting the session in your `LoginController`?

Yes

**Comment by mychidarko** [comment]
Alright, pls try this instead.

There's a base controller in the `App\Controllers` directory. One advantage of that file is that you can initialize packages in there and use them throughout all your individual Controllers once they extend it.

So please locate `App\Controllers\Controller.php` and do something like this:

```php
<?php

namespace App\Controllers;

/**
 * This is the base controller for your Leaf API Project.
 * You can initialize packages here to use them across
 * all your other controllers which extend this one.
 */
class Controller extends \Leaf\Controller
{
	public $session;

	public function __construct()
	{
		parent::__construct();
                // ...
		session_start();
		$this->session = new \Leaf\Http\Session;
		$this->session->id();
	}
}
```

**Comment by mychidarko** [comment]
So you initialize the session in the base controller, and then, you can use the session in your `LoginController`

```php
// ...
$this->session->set("example", "something");
$this->session->get("example");
```

**Comment by arnoclr** [comment]
> Hello, I try your solution but I've an other error :
> 
> `Fatal error: Uncaught ErrorException: session_id(): Cannot change session id when session is active in C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php:175 Stack trace: #0 [internal function]: Leaf\App::handleErrors(2, 'session_id(): C...', 'C:\\xampp\\htdocs...', 175, Array) #1 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php(175): session_id('884rm99pjaj56i1...') #2 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php(16): Leaf\Http\Session->id() #3 C:\xampp\htdocs\App\Controllers\LoginController.php(39): Leaf\Http\Session->__construct() #4 [internal function]: App\Controllers\LoginController->mail() #5 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\App.php(754): call_user_func_array(Array, Array) #6 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\App.php(727): Leaf\App->invoke('LoginController...', Array) #7 C:\xampp\htdocs\vendor\leafs\leaf\Leaf\App.php(1297): Leaf\App->handle(Array, true) #8 C:\xampp\htdocs\index.php(107): Leaf\App->run() #9 {main} thrown in C:\xampp\htdocs\vendor\leafs\leaf\Leaf\Http\Session.php on line 175`

Thanks you, but I've the same error 😞

**Comment by mr-phlames** [comment]
Does the same thing happen if you use `$this->session->get("id");`?

**Comment by mychidarko** [comment]
Can you make sure you're not initializing `Leaf\Http\Session` twice, or using `session_start` twice?

**Comment by arnoclr** [comment]
I just copy paste your code on Controller, and I dont use leaf session or session start in other file

**Comment by mychidarko** [comment]
Alright, then for now, pls stick to default PHP sessions while this problem is being fixed. Once again sorry for the inconvenience ☹️

**Comment by arnoclr** [comment]
that's what I did, i will wait. Thanks 👍

**Comment by mychidarko** [comment]
Thank you too🙂
