### ISSUE TITLE
DB_PORT will never be used

### ISSUE THREAD

**Issue by pjotrsavitski** [leafsphp/leafMVC#6]
It seems that `DB_PORT` environment value will never be used will never be used with database connection as could be clearly seen from [here](https://github.com/leafsphp/leaf/blob/v2.x/src/Database.php#L16).

Passing it is still possible by adding the port number to the `DB_HOST` as `127.0.0.1:3333`

**Comment by mychidarko** [comment]
@pjotrsavitski Thanks for pointing this out. This is a really huge oversight and I'm really sorry for any inconvenience caused😨

**Comment by mychidarko** [comment]
I'll have this fixed in the next leaf release, ideally you can make a pull request with the fix yourself. Thanks for your support

**Comment by pjotrsavitski** [comment]
No inconveniences caused as I was just checking things out. I'll see if I can make a pull request out of it, no promises made.

**Comment by pjotrsavitski** [comment]
I've made several pull requests that should deal with this issue and a few others. Aloe also needed to have a separate handling of the port setting for `db:install` command.

The code was unfortunately written in the GitHub web editor, which means that I've not tested it in any way. I did write some directly into the fetched dependencies, but didn't copy it.
