### ISSUE TITLE
Help me! I would like to change the folder structure

### ISSUE THREAD

**Issue by lostov** [leafsphp/leafMVC#7]
Hi guys
I have one problem, i need change the web assets path (assets = js + css + image + fonts) from root directory to inside public or storage dir!
What i need do with .htaccess?

**Comment by mychidarko** [comment]
Hi, thanks for reaching out. Well, that shouldn't really matter. Your
htaccess just needs to point to the index.php file.

**Comment by mychidarko** [comment]
After changing your assets path, you also need to update that in config/paths.php. From there, everything should work fine

**Comment by lostov** [comment]
> After changing your assets path, you also need to update that in config/paths.php. From there, everything should work fine

Hi, I am grateful for your answer!
Can you help me? What exactly do I need to add the file will change in the file?

**Comment by lostov** [comment]
`<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(?:[^/]*/)*([^/.]+\.(?:jpe?g|gif|bmp|png|tiff|css|js))$ /storage/app/public/$1 [R=301,L,NC]
    RewriteRule ^ index.php [L]
</IfModule>
`
Im added this code to .htaccess before **RewriteRule** of index.php
` RewriteRule ^(?:[^/]*/)*([^/.]+\.(?:jpe?g|gif|bmp|png|tiff|css|js))$ /storage/app/public/$1 [R=301,L,NC]`
but, it does not working, why i dunno?

**Comment by mychidarko** [comment]
No you don't need to add a rewrite rule for your assets, just the link the new path of your index.php. If you won't move your index.php from your project root, then there's no need to edit the htaccess file

**Comment by mychidarko** [comment]
Btw, the assets are inside the views directory not in the root directory. After moving them to the public folder, you just need to reference them using `public_path`

Eg: `public_path("js/index.js");`
