### ISSUE TITLE
Error with db:migrate command

### ISSUE THREAD

**Issue by Aminur670** [leafsphp/leafMVC#8]
# Please Fix Issues with  `php leaf db:migrate` ,command in Leaf's next(2.6) stable release.
@mychidarko 
> ##  It's still not working science leaf 2.0 and thousands of software engineers loving it's simple but powerful & clean way .

Structure of leaf framework is way better framework right now.
But, automatic database migration just became bigger issue with this killer framework.
I don't know why you guys still keeping this issue from leaf 2.0 !!!
I've tried few patch, but nothing worked.
So, please kindly fix it.

**Comment by mychidarko** [comment]
Hi @Aminur670, can I have a look at the database configuration fields in your .env file. You can remove the values if there's anything sensitive in there.

**Comment by mychidarko** [comment]
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=LEAF_DB_NAME
DB_USERNAME=LEAF_DB_USERNAME
DB_PASSWORD=
DB_CHARSET=utf8
DB_COLLATION=utf8_unicode_ci

Pls confirm that you have the charset and collation fields

**Comment by Aminur670** [comment]
># Take love from bottom of heart & Thanks a lot !!!!
Finally It's Working.

**Comment by mychidarko** [comment]
Awesome🔥

**Comment by Aminur670** [comment]
And please don't remove blade form Leaf's MVC or Skeleton. Just, let the blade instance be there. 
And Vue or Svelte integration with Leaf would be something great I hope.

Commands would be like bellow:
- `php leaf ui:vue` or `php leaf ui:react` or `php leaf ui:svelte` ,
You will find about it in frontend section of laravel 7.x docs .

thanks a lot for your valuable time and great works.

**Comment by mychidarko** [comment]
Well, @Aminur670, it's unfortunate but Blade will not shipped with Skeleton's upcoming v3 release by default anymore, it will instead come with [Leaf's BareUI](https://www.leafphp.dev/docs/modules/views/bareui.html). This is to make Skeleton lighter and even faster than it currently is, you can always install blade with `composer require leafs/blade` or `leaf install blade` if you're using [Leaf CLI](https://www.leafphp.dev/cli/). It will stay in leaf mvc though.

For the UI scaffolds, I'll add those as a feature request.
